apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: endolla-mysql
  namespace: endolla-watcher
  labels:
    app.kubernetes.io/name: endolla-mysql
    app.kubernetes.io/component: database
spec:
  serviceName: endolla-mysql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: endolla-mysql
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: endolla-mysql
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - secretRef:
                name: endolla-mysql-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mysqladmin ping -h 127.0.0.1
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mysqladmin ping -h 127.0.0.1
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
