apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: endolla-watcher
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dewgenenny/endolla_watcher.git
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: endolla-watcher
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
